version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.10
      
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run tests
          command: pytest --cov=src

workflows:
  sample: 
    jobs:
      - test-python
