version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test-python:
    working_directory: api

    docker:
      - image: cimg/python:3.10
      
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Testing Python
          command: pytest -v --cov=src --cov-report=term-missing

  test-js:
    docker:
      - image: cimg/node:16.10.0

    steps:
      - checkout

      - run:
         name: Installing environment
         command: yarn install

      - run:
         name: Testing Javascript
         command: yarn test

workflows:
  sample: 
    jobs:
      - test-js
      - test-python
